# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
locale: es_ES

# Site title
title: "Por hablar de otra cosa"

# A description of your site for meta tag, search engine results.
description: "Una vez yo escribía un blog"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: "/blog"

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://yrjo.tk"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: ¿Qué es esto?
    url: /blog/bio

# The shortname for your Disqus site to enable comments.
disqus: 

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: ""
  has_social: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
  
# prose.io config
prose:
  rooturl: ''
  media: 'img'
  ignore:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Título del artículo"
          placeholder: "Titulo"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtítulo"
          placeholder: "Una descripción de tu artículo"
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Fecha"
          help: "Introduce la fecha de publicación"
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Imagen"
          help: "Añade una imagen a tu artículo"
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicar"
          help: "Marca para publicar, desmarca para ocultar."
